# basic options
title: Cref's Geeky space
author: Crefeda Rodrigues
email: crefeda.rodrigues@postgrad.manchester.ac.uk
description: Green AI
twitter_username: crefeda
github_username: Crefeda

# Build settings
markdown: kramdown
theme: minima
