# basic options
title: Cref's Thinkspace
author: Crefeda Rodrigues
email: crefeda.rodrigues@manchester.ac.uk
description: Green AI
twitter_username: crefeda
github_username: Crefeda
linkedin_username: crefedarodrigues
# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
