# basic options
title: Cref's Geeky space
author: Crefeda Rodrigues
email: your-email@domain.com
description: Green AI
twitter_username: @crefeda
github_username: Crefeda

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
